# kubernetes/librechat-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: librechat
  namespace: librechat
  labels:
    app: librechat
spec:
  type: NodePort
  selector:
    app: librechat
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 3080
      nodePort: 31180
