# kubernetes/librechat-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librechat
  namespace: librechat
  labels:
    app: librechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librechat
  template:
    metadata:
      labels:
        app: librechat
    spec:
      containers:
        - name: librechat
          image: ghcr.io/danny-avila/librechat:v0.7.8
          ports:
            - containerPort: 3080
              protocol: TCP
          envFrom:
            - secretRef:
                name: librechat-secrets
          env:
            - name: DOMAIN_CLIENT
              value: "https://ai.andex.tokyo/"
            - name: ALLOW_REGISTRATION
              value: "true"
            - name: APP_TITLE
              value: "Akihabara AI Chat"
            - name: ENDPOINTS
              value: "google,bedrock,openAI"
            - name: BEDROCK_AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: BEDROCK_AWS_MODELS
              value: "amazon.nova-lite-v1:0,amazon.nova-pro-v1:0,us.amazon.nova-premier-v1:0,us.anthropic.claude-3-5-haiku-20241022-v1:0,us.anthropic.claude-sonnet-4-20250514-v1:0,us.anthropic.claude-3-7-sonnet-20250219-v1:0"
            - name: GOOGLE_MODELS
              value: "gemini-2.5-flash-preview-05-20,gemini-2.5-pro-preview-05-06"
            - name: OPENAI_MODELS
              value: "gpt-4.1-2025-04-14,o4-mini-2025-04-16,gpt-4.1-mini-2025-04-14"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: librechat-data
              mountPath: /app/data
      volumes:
        - name: librechat-data
          persistentVolumeClaim:
            claimName: librechat-data-pvc
