# kubernetes/librechat-data-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librechat-data-pvc
  namespace: librechat
  labels:
    app: librechat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
