# kubernetes/librechat-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librechat
  namespace: librechat
  labels:
    app: librechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librechat
  template:
    metadata:
      labels:
        app: librechat
    spec:
      containers:
        - name: librechat
          image: ghcr.io/danny-avila/librechat:v0.7.7
          ports:
            - containerPort: 3080
              protocol: TCP
          envFrom:
            - secretRef:
                name: librechat-secrets
          env:
            - name: AUTH_TYPE
              value: "openid"
            - name: OPENID_CLIENT_ID
              value: "26P8j2RzDJgO2BiX"
            - name: OPENID_ISSUER
              value: "https://clerk.ai.andex.tokyo/.well-known/openid-configuration"
            - name: OPENID_SCOPES
              value: "openid profile email"
            - name: DOMAIN_CLIENT
              value: "https://ai.andex.tokyo/"
            - name: OPENID_CALLBACK_URL
              value: "https://ai.andex.tokyo/oauth/openid/callback"
            - name: ALLOW_REGISTRATION
              value: "true"
            - name: APP_TITLE
              value: "Akihabara AI Chat"
            - name: ENDPOINTS
              value: "google,bedrock"
            - name: BEDROCK_AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: BEDROCK_AWS_MODELS
              value: "anthropic.claude-3-5-sonnet-20241022-v2:0,anthropic.claude-3-7-sonnet-20250219-v1:0"
            - name: GOOGLE_MODELS
              value: "gemini-2.5-flash-preview-04-17,gemini-2.5-pro-preview-03-25"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: librechat-data
              mountPath: /app/data
      volumes:
        - name: librechat-data
          persistentVolumeClaim:
            claimName: librechat-data-pvc
