apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data-pvc
  namespace: librechat
  labels:
    app: meilisearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
