# kubernetes/open-webui-service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: webui
  name: open-webui-service
  labels:
    app: open-webui
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31180
